### ISSUE TITLE
rsyslog.service getting stuck in a restart loop due to pid 1 already being present

### ISSUE THREAD

**Issue by rubenst2013** [jumanjihouse/docker-rsyslog#25]
Our rsyslog.service container, managed via docker compose, frequently got stuck in a restart loop.

Its own logs says over and over:
`rsyslog.service    | rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)
rsyslog.service    | rsyslogd: pidfile '/var/run/rsyslogd.pid' and pid 1 already exist.
rsyslog.service    | If you want to run multiple instances of rsyslog, you need to specify
rsyslog.service    | different pid files for them (-i option).`

Some quick research on the web found that by removing /var/run/rsyslogd.pid during container startup, just before rsyslogd is called, the issue can be resolved. Read here: 
[https://github.com/goharbor/harbor/pull/1197](https://github.com/goharbor/harbor/pull/1197)

Would be awesome if you could add the equivalent change here as well. :)

**Comment by jumanjiman** [comment]
@rubenst2013 Thanks for the tip!
